FROM python:3.9-alpine as base

FROM base as builder

COPY requirements.txt /requirements.txt
RUN pip install --user -r /requirements.txt

FROM base

COPY --from=builder /root/.local /root/.local
COPY src /app

ENV PATH=/root/.local/bin:$PATH
WORKDIR /app

CMD ["python3", "-m" , "flask", "run", "--host=0.0.0.0"]
